# Generated by Django 5.1.2 on 2024-12-09 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_agent_phone_alter_customer_phone'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='')),
                ('serial', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('percent', models.BigIntegerField()),
                ('price', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('credit', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_contracts', to=settings.AUTH_USER_MODEL)),
                ('buyer_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to='accounts.customer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.file')),
                ('seller_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
    ]
