# Generated by Django 5.1.2 on 2024-12-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
    ]
