# Generated by Django 5.1.2 on 2024-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_image_remove_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
