# Generated by Django 5.1.2 on 2024-12-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_agent_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('area', models.PositiveIntegerField()),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('prepayment', models.BigIntegerField(blank=True, null=True)),
                ('rent', models.BigIntegerField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.file')),
                ('floor', models.PositiveIntegerField()),
                ('parkings', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('build_year', models.PositiveIntegerField(default=0)),
                ('basement', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
            ],
            bases=('home.file',),
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.file')),
                ('build_year', models.PositiveIntegerField()),
                ('has_gazebo', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('yard_area', models.PositiveIntegerField()),
            ],
            bases=('home.file',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.file')),
            ],
            bases=('home.file',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.file')),
                ('build_year', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('parkings', models.PositiveIntegerField()),
            ],
            bases=('home.file',),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.file')),
                ('build_year', models.PositiveIntegerField()),
                ('yard_area', models.PositiveIntegerField()),
                ('parkings', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('basement', models.BooleanField(default=False)),
            ],
            bases=('home.file',),
        ),
    ]
