# Generated by Django 5.1.2 on 2024-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_file_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
