# Generated by Django 5.1.2 on 2024-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
