# Generated by Django 5.1.2 on 2024-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_visitrequest_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
