# Generated by Django 5.1.2 on 2024-12-09 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agent_phone_alter_customer_phone'),
        ('requests', '0003_visitrequest_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('villa', 'ویلا'), ('apartment', 'آپارتمان'), ('land', 'زمین'), ('store', 'فروشگاه'), ('garden', 'باغ')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expert_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expertises', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_requests', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'درخواست کارشناسی',
                'verbose_name_plural': 'درخواست\u200cهای کارشناسی',
            },
        ),
    ]
