# Generated by Django 5.1.2 on 2024-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_expertiserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiserequest',
            name='expertise_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='expertiserequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
