# Generated by Django 5.1.2 on 2024-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_expertiserequest_expertise_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20),
        ),
    ]
